# Generated by Django 5.1.6 on 2025-02-27 13:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_alter_results_options_exams_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidTermExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semester', models.IntegerField()),
                ('academic_year', models.CharField(help_text='Format: YY/YY (e.g., 24/25)', max_length=5, null=True, validators=[django.core.validators.RegexValidator(message="Academic year must be in the format 'YY/YY' (e.g., '24/25').", regex='^\\d{2}/\\d{2}$')])),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.classname')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.subject')),
            ],
        ),
    ]
