# Generated by Django 5.1.6 on 2025-03-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_midtermexams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midtermexams',
            options={'verbose_name_plural': 'MidTermExams'},
        ),
    ]
