# Generated by Django 5.1.6 on 2025-03-07 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_alter_midtermexams_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.classname'),
        ),
    ]
