# Generated by Django 5.1.6 on 2025-03-08 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_subject_class_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JHS3',
        ),
    ]
